# Все импорты из reply.py удалены - теперь используется только inline.py
from .inline import (
    get_post_generation_keyboard,
    get_main_menu_keyboard,
    get_content_creation_menu_keyboard,
    get_content_form_menu_keyboard,
    get_ngo_info_menu_keyboard,
    get_ngo_data_missing_keyboard,
    get_content_type_keyboard,
    get_yes_no_keyboard,
    get_navigation_keyboard,
    get_generation_mode_keyboard,
    get_narrative_style_keyboard,
    get_goal_keyboard,
    get_audience_keyboard,
    get_platform_keyboard,
    get_format_keyboard,
    get_volume_keyboard,
    get_period_keyboard,
    get_frequency_keyboard,
    get_skip_keyboard,
    get_ngo_main_keyboard,
    get_ngo_navigation_keyboard,
)

__all__ = [
    "get_post_generation_keyboard",
    "get_main_menu_keyboard",
    "get_content_creation_menu_keyboard",
    "get_content_form_menu_keyboard",
    "get_ngo_info_menu_keyboard",
    "get_ngo_data_missing_keyboard",
    "get_content_type_keyboard",
    "get_yes_no_keyboard",
    "get_navigation_keyboard",
    "get_generation_mode_keyboard",
    "get_narrative_style_keyboard",
    "get_goal_keyboard",
    "get_audience_keyboard",
    "get_platform_keyboard",
    "get_format_keyboard",
    "get_volume_keyboard",
    "get_period_keyboard",
    "get_frequency_keyboard",
    "get_skip_keyboard",
    "get_ngo_main_keyboard",
    "get_ngo_navigation_keyboard",
]
